export class CloudBackupCreate {
  customerId: number
  userEmail: string
  actorEmail: string
  projectId: string
  vpcId: string
  regionId: number
  serviceName: string
  serviceType: number
  actionType: number
  serviceInstanceId: number
  createDate: Date
  expireDate: Date
  createDateInContract: string
  saleDept: string
  saleDeptCode: string
  contactPersonEmail: string
  contactPersonPhone: string
  contactPersonName: string
  am: string
  amManager: string
  note: string
  isTrial: boolean
  offerId: number
  offerPriceType: string
  couponCode: string
  dhsxkd_SubscriptionId: string
  dSubscriptionNumber: string
  dSubscriptionType: string
  oneSMEAddonId: string
  oneSME_SubscriptionId: string
  isSendMail: boolean
  typeName: string
  name: string
  storage: number
  description: string
  quotaCloudBackup: number
}