services:
  app-host:
    image: repo.onsmartcloud.com/cloudportal/app-host
    build:
      context: ./
      dockerfile: apps/app-host/Dockerfile
    container_name: app-host
    restart: on-failure
    expose:
      - '4200'
    ports:
      - "4200:80"
    environment:
      - APP_SMART_CLOUD_URL=https://appsmartcloud.onsmartcloud.com
      - APP_KUBERNETES_URL=https://appkubernetes.onsmartcloud.com
      - APP_KAFKA_URL=https://appkafka.onsmartcloud.com
      - APP_K8S_PREMIUM_URL=https://appk8spre.onsmartcloud.com
      - APP_ECR_URL=https://apperc.onsmartcloud.com
      - BASE_URL=https://api.onsmartcloud.com
      - ISSUER=https://identity.onsmartcloud.com
      - CLIENT_ID=frontend-client
      - CALLBACK=http://localhost:4200/passport/callback/oneportal
      - LOGOUT_CALLBACK=http://localhost:4200
      - SCOPE=openid profile email

  app-smartcloud:
    image: repo.onsmartcloud.com/cloudportal/app-smartcloud
    build:
      context: ./
      dockerfile: apps/app-smart-cloud/Dockerfile
    container_name: app-smartcloud
    restart: on-failure
    expose:
      - '4203'
    ports:
      - "4203:80"