services:
  app-host:
    image: crelease.devops.vnpt.vn:22222/cloudportal-product/app-host:170724
    build:
      context: ./
      dockerfile: apps/app-host/Dockerfile_prod
    container_name: app-host
    restart: on-failure
    expose:
      - '4200'
    ports:
      - "4200:80"

  app-smartcloud:
    image: crelease.devops.vnpt.vn:22222/cloudportal-product/app-smartcloud:170724
    build:
      context: ./
      dockerfile: apps/app-smart-cloud/Dockerfile_prod
    container_name: app-smartcloud
    restart: on-failure
    expose:
      - '4203'
    ports:
      - "4203:80"