services:
  app-host:
    image: repo.onsmartcloud.com/cloudportal-dev/app-host
    build:
      context: ./
      dockerfile: apps/app-host/Dockerfile_dev
    container_name: app-host
    restart: on-failure
    expose:
      - '4200'
    ports:
      - "4200:80"

  app-smartcloud:
    image: repo.onsmartcloud.com/cloudportal-dev/app-smartcloud
    build:
      context: ./
      dockerfile: apps/app-smart-cloud/Dockerfile_test-dbp
    container_name: app-smartcloud
    restart: on-failure
    expose:
      - '4203'
    ports:
      - "4203:80"