apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-host-deployment
  namespace: vnptcloud
  labels:
    app: app-host
spec:
  replicas: 1
  selector:
    matchLabels:
      service: app-host
  template:
    metadata:
      labels:
        app: app-host
        service: app-host
    spec:
      containers:
        - name: app-host
          image: registry.onsmartcloud.com/cloudportal/oneportal-app-host
          ports:
            - containerPort: 80
              protocol: TCP
      imagePullSecrets:
        - name: regcred
#          env:
#            - name: API_LINK
#              value: http://localhost:30991
---
apiVersion: v1
kind: Service
metadata:
  name: app-host
  namespace: vnptcloud
spec:
  type: NodePort
  ports:
    - port: 80
      name: port1
      nodePort: 30766
  selector:
    app: app-host
