version: "3.8"
services:
  #----------------------------------------------------------------
  app-host:
    image: app-host:1.0.0
    build:
      context: ./..
      dockerfile: apps/app-host/Dockerfile
    container_name: app-host
    restart: on-failure
    expose:
      - '4200'
    ports:
      - "4200:80"
    networks:
      - one-portal-network

  #  ----------------------------------------------------------------
  app-smart-cloud:
    image: app-smart-cloud:1.0.0
    build:
      context: ./..
      dockerfile: apps/app-smart-cloud/Dockerfile
    container_name: app-smart-cloud
    restart: on-failure
    expose:
      - '4203'
    ports:
      - "4203:80"
    networks:
      - one-portal-network
#----------------------------------------------------------------
networks:
  one-portal-network:
