export class VmDto {
  id: number;
  name: string;
  // cloudId: string;
  // name: string;
  // flavorId: number;
  // flavorCloudId: string;
  // imageId: number;
  // customerId: number;
  // ipPublic: string;
  // ipPrivate: string;
  // cpu: string;
  // ram: string;
  // storage: string;
  // initPassword: string;
  // preResizeInstanceId: string | null;
  // regionId: number;
  // regionText: string;
  // createdDate: string;
  // cloudIdentityId: number;
  // projectName: string;
  // projectId: number;
  // bttn: string | null;
  // btqt: string | null;
  // ramAdditional:string | null ;
  // cpuAdditional: string | null;
  // bttnAdditional: string | null;
  // btqtAdditional: string | null;
  // volumeRootId: number;
  // status: string;
  // taskState: string | null;
  // project: string | null;
  // id: number;
}
