export class VolumeDTO {
    cloudId: string;
    name: string;
    sizeInGB: number;
    description: string;
    instanceId: string;
    postResizeVolumeId: string;
    bootable: boolean;
    regionId: number;
    regionText: string;
    offerId: string;
    iops: number;
    customerId: string;
    createDate: string;
    status: string;
    cloudIdentityId: number;
    projectName: string;
    projectId: number;
    instanceName: string;
    expireDate: string;
    deletedDate: string;
    suspendDate: string;
    serviceStatus: string;
    suspendType: string;
    typeId: string;
    backupScheduleId: string;
    vpcId: string;
    vpcName: string;
    isEncryption: string;
    isMultiAttach: string;
    volumeType: string;
    customerEmail: string;
    id: 12573
}
