apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vnptcloud
  name: ${APP_NAME}
  labels:
    app: ${APP_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      service: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
        service: ${APP_NAME}
    spec:
      containers:
        - name: ${APP_NAME}
          image: ${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
      imagePullSecrets:
        - name: regcred