export interface BackupVolume {
  id: number
  name: string
  size: number
  description: string
  volumeId: number
  cloudId: string
  regionId: number
  customerId: number
  scheduleId: number
  instanceBackupId: number
  isBootable: true
  iops: number
  offerId: number
  cloudIdentity: number
  projectName: string
  projectId: number
  backupPackageId: number
  status: string
  typeName: string
  volumeName: string
  serviceStatus: string
  creationDate: Date
  expirationDate: Date
  suspendDate: Date
  suspendType: string
  vpcName: string
  customerEmail: string
  backupPackageName: string
}
